# Generated by Django 4.0.4 on 2022-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_carrito',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Items_carrito'),
        ),
        migrations.AlterModelTable(
            name='items_carrito',
            table='db_Items_carrito',
        ),
    ]
